language: go

install:
- go get github.com/mattn/goveralls
- ./travis/install_gcloud.sh kubectl
- go get -t ./...

script:
- go test -v -coverprofile=coverage.out ./...
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

deploy:
# Sandbox
- provider: script
  script: ./travis/kubectl.sh mlab-sandbox prometheus-federation ./deploy_gmx.sh
  on:
    repo: m-lab/github-maintenance-exporter
    branch: sandbox-*
    condition: "$TRAVIS_EVENT_TYPE == push"
# Staging
- provider: script
  script: ./travis/kubectl.sh mlab-staging prometheus-federation ./deploy_gmx.sh
  on:
    repo: m-lab/github-maintenance-exporter
    branch: master
    condition: "$TRAVIS_EVENT_TYPE == push"
# Production
- provider: script
  script: ./travis/kubectl.sh mlab-oti prometheus-federation ./deploy_gmx.sh
  on:
    repo: m-lab/github-maintenance-exporter
    tags: true
